(setq default-frame-alist '((background-color . "gray5")
			    (foreground-color . "white")
			    (font . "Hack-11")
			    (tool-bar-lines)
			    (menu-bar-lines)
			    (horizontal-scroll-bars)
			    (vertical-scroll-bars)))
