(setq default-frame-alist '((font . "DejaVu Sans Mono-11")
			    (background-color . "gray95")
			    (width . 100)
			    (height . 40)
			    (vertical-scroll-bars)
			    (horizontal-scroll-bars)
			    (tool-bar-lines)
			    (menu-bar-lines)))
