(setq default-frame-alist '((font . "DejaVu Sans Mono-11")
			    (background-color . "#1a2024")
			    (foreground-color . "#ffffff")
			    (width . 100)
			    (height . 40)
			    (vertical-scroll-bars)
			    (horizontal-scroll-bars)
			    (tool-bar-lines)
			    (menu-bar-lines)))
